# Generated by Django 5.0.6 on 2025-01-15 18:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BingoDailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_winning', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cut', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_transactions', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BingoTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.JSONField(default=list)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('game_type', models.CharField(max_length=100)),
                ('bet', models.DecimalField(decimal_places=2, max_digits=10)),
                ('player_number', models.PositiveIntegerField()),
                ('total_won', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cut', models.DecimalField(decimal_places=2, max_digits=10)),
                ('won', models.DecimalField(decimal_places=2, max_digits=10)),
                ('call_number', models.PositiveIntegerField()),
                ('winners', models.PositiveIntegerField()),
                ('started', models.BooleanField(default=False)),
                ('ended', models.BooleanField(default=False)),
                ('daily_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bingo.bingodailyrecord')),
            ],
        ),
        migrations.CreateModel(
            name='BingoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=1000, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('branch', models.CharField(default='ahadu_bingo', max_length=100)),
                ('cut_percentage', models.PositiveIntegerField(default=25)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bingodailyrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bingo_record', to='bingo.bingouser'),
        ),
    ]
