# Generated by Django 5.0.6 on 2025-01-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0002_alter_bingotransaction_options_alter_bingouser_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingotransaction',
            name='game_pattern',
            field=models.CharField(default='two_line', max_length=100),
        ),
    ]
