# Generated by Django 5.0.6 on 2025-01-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0003_bingotransaction_game_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingotransaction',
            name='game_pattern',
            field=models.CharField(choices=[('default', 'Default Pattern'), ('full_house', 'Full House'), ('two_line', 'Two Lines'), ('one_line', 'One Line'), ('three_line', 'Three Lines'), ('four_line', 'Four Lines'), ('corners', 'Corners Only'), ('any_vertical', 'Any Vertical'), ('any_horizontal', 'Any Horizontal'), ('any_2_vertical', 'Any 2 Vertical'), ('any_2_horizontal', 'Any 2 Horizontal'), ('any_diagonal', 'Any Diagonal'), ('any_1_corner', 'Any 1 Corner Square'), ('any_2_corner', 'Any 2 Corner Squares'), ('any_3_corner', 'Any 3 Corner Squares'), ('all_4_corners', 'All 4 Corner Squares'), ('any_2_lines', 'Any 2 Lines'), ('any_3_lines', 'Any 3 Lines'), ('4_middle', '4 Single Middle'), ('inner_outer', '4 Inner, 4 Outer')], default='default', max_length=50),
        ),
    ]
