# Generated by Django 5.0.6 on 2025-01-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0005_alter_bingotransaction_game_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingotransaction',
            name='winners',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
