# Generated by Django 5.0.6 on 2025-01-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0006_alter_bingotransaction_winners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingotransaction',
            name='winners',
            field=models.CharField(max_length=10),
        ),
    ]
