# Generated by Django 5.0.6 on 2025-01-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0007_alter_bingotransaction_winners'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingotransaction',
            name='transaction_id',
            field=models.PositiveIntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bingotransaction',
            name='winners',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
