# Generated by Django 5.0.6 on 2025-01-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0008_bingotransaction_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingotransaction',
            name='submitted_cartella',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='bingotransaction',
            name='winners',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
