# Generated by Django 5.0.6 on 2025-01-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0010_remove_bingotransaction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingotransaction',
            name='transaction_id',
            field=models.PositiveIntegerField(default=True),
            preserve_default=False,
        ),
    ]
