# Generated by Django 5.0.6 on 2025-01-20 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0011_bingotransaction_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bingotransaction',
            name='transaction_id',
        ),
    ]
