# Generated by Django 5.0.6 on 2025-01-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0014_bingotransaction_refunded'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingotransaction',
            name='locked_cartella',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
