# Generated by Django 5.0.6 on 2025-01-25 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0016_alter_bingouser_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingotransaction',
            name='game_pattern',
            field=models.CharField(choices=[('default', 'Default Pattern'), ('any_two', 'Any Two Pattern'), ('full_house', 'Full House'), ('one_line', 'One Line'), ('two_line', 'Two Lines'), ('three_line', 'Three Lines'), ('four_line', 'Four Lines'), ('corners', 'Corners Only'), ('any_vertical', 'Any Vertical'), ('any_horizontal', 'Any Horizontal'), ('any_diagonal', 'Any Diagonal'), ('any_2_vertical', 'Any 2 Vertical'), ('any_2_horizontal', 'Any 2 Horizontal'), ('any_2_diagonal', 'Any 2 Diagonal'), ('four_middle', '4 Single Middle'), ('inner_outer', '4 Inner, 4 Outer')], default='default', max_length=50),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bingo.bingouser')),
            ],
        ),
    ]
