# Generated by Django 5.0.6 on 2025-01-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0017_alter_bingotransaction_game_pattern_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
