# Generated by Django 5.0.6 on 2025-02-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0021_alter_bingotransaction_game_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingouser',
            name='show_balance',
            field=models.BooleanField(default=True),
        ),
    ]
