# Generated by Django 5.0.6 on 2025-02-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0022_bingouser_show_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingotransaction',
            name='single_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
