# Generated by Django 5.0.6 on 2025-02-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0023_bingotransaction_single_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingouser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
