GAME_PATTERN_CHOICES = [
    ("default", "Default Pattern"),
    ("any_two", "Any 2 Pattern"),
    ("full_house", "ሙሉ ቤት"),
    ("one_line", "1 መስመር"),
    ("two_line", "2 መስመር"),
    ("three_line", "3 መስመር"),
    ("four_line", "4 መስመር"),
    ("corners", "Corners Only"),
    ("any_vertical", "የትኛውም 1 ወደ ታች"),
    ("any_horizontal", "የትኛውም 1 ወደ ጎን"),
    ("any_diagonal", "የትኛውም Diagonal"),
    ("any_2_vertical", "የትኛውም 2 ወደ ታች"),
    ("any_2_horizontal", "የትኛውም 2 ወደ ጎን"),
    ("any_2_diagonal", "2 Diagonal"),
    ("four_middle", "4 Single Middle"),
    ("inner_outer", "4 Inner, 4 Outer"),
    # ("any_1_corner", "የትኛውም 1 Corner Square"),
    # ("any_2_corner", "የትኛውም 2 Corner Squares"),
    # ("any_3_corner", "የትኛውም 3 Corner Squares"),
    # ("all_4_corners", "All 4 Corner Squares"),
    # ("any_3_lines", "የትኛውም 3 መስመር"),
]
