GAME_PATTERN_CHOICES = [
    ("default", "Default Pattern"),
    ("any_two", "Any Two Pattern"),
    ("full_house", "Full House"),
    ("two_line", "Two Lines"),
    ("one_line", "One Line"),
    ("three_line", "Three Lines"),
    ("four_line", "Four Lines"),
    ("corners", "Corners Only"),
    ("any_vertical", "Any Vertical"),
    ("any_horizontal", "Any Horizontal"),
    ("any_2_vertical", "Any 2 Vertical"),
    ("any_2_horizontal", "Any 2 Horizontal"),
    ("any_diagonal", "Any Diagonal"),
    # ("any_1_corner", "Any 1 Corner Square"),
    # ("any_2_corner", "Any 2 Corner Squares"),
    # ("any_3_corner", "Any 3 Corner Squares"),
    # ("all_4_corners", "All 4 Corner Squares"),
    ("any_2_lines", "Any 2 Lines"),
    ("any_3_lines", "Any 3 Lines"),
    # ("4_middle", "4 Single Middle"),
    # ("inner_outer", "4 Inner, 4 Outer"),
]
