# Generated by Django 5.0.6 on 2025-02-07 15:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offline_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offlineusers',
            name='branch',
        ),
        migrations.AddField(
            model_name='offlineusers',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='offlineusers',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
